# Generated by Django 3.1.2 on 2020-11-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdelivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('is_busy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musterinin_ad', models.CharField(max_length=50)),
                ('musterinin_soyadi', models.CharField(max_length=50)),
                ('musterinin_sifarisi', models.CharField(max_length=50)),
                ('musterinin_nomresi', models.CharField(blank=True, max_length=15)),
                ('kuryerin_adi', models.CharField(max_length=50)),
                ('kuryerin_soyadi', models.CharField(max_length=50)),
                ('kuryerin_nomresi', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(max_length=250)),
                ('total', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='musterinin_sifarisi',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='total',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
