# Generated by Django 2.2.12 on 2020-11-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backdelivery', '0002_auto_20201116_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverypackages',
            old_name='musterinin_ad',
            new_name='musterinin_adi',
        ),
    ]
