# Generated by Django 3.1 on 2020-11-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdelivery', '0003_auto_20201122_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recency', models.FloatField()),
                ('Frequency', models.FloatField()),
                ('Monetary', models.FloatField()),
                ('R', models.FloatField()),
                ('F', models.FloatField()),
                ('M', models.FloatField()),
                ('RFMGroup', models.FloatField()),
                ('RFMScore', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rfmscores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recency', models.CharField(max_length=50)),
                ('Frequency', models.CharField(max_length=50)),
                ('Monetary', models.CharField(max_length=50)),
                ('R', models.CharField(max_length=50)),
                ('F', models.CharField(max_length=50)),
                ('M', models.CharField(max_length=50)),
                ('RFMGroup', models.CharField(max_length=50)),
                ('RFMScore', models.CharField(max_length=50)),
            ],
        ),
    ]
