# Generated by Django 3.1 on 2020-11-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backdelivery', '0004_predresults_rfmscores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rfmscores',
        ),
    ]
