# Generated by Django 3.1.2 on 2020-11-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdelivery', '0006_deliverypackages_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='time',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
    ]
